version: "3"

services:
        db:
                build: ./mysql
                container_name: db
                ports:
                        - "3306:3306"

        web:
                build: ./expressjssnap
                container_name: web
                ports:
                        - "8080:8080"

        traffic:
                build: ./nginx
                container_name: traffic
                ports:
                        - "5005:5005"
                depends_on:
                        - web
               